version: 2

builds:
  - binary: gokazi
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    flags:
      - -trimpath
      - -tags=safe
    ldflags:
      - -s -w -X github.com/foomo/gokazi/cmd.version={{.Version}}

release:
  prerelease: auto

archives:
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  use: github-native

brews:
  - repository:
      owner: foomo
      name: homebrew-tap
    caveats: "gokazi -h"
    homepage: "https://github.com/foomo/gokazi"
    description: "Simple daemonmless process manager"
    test: |
      system "#{bin}/gokazi --version"
